### ISSUE TITLE
ValueError: The channel dimension of the inputs should be defined. Found `None`.

### ISSUE THREAD

**Issue by shinebay** [HiiYL/vision-flask-demo#1]
Thanks for sharing this project, when I test piqual, it returns this error:

> Using TensorFlow backend.
> /home/website/i4/piqual/model.py:16: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(64, (3, 3), padding="same", activation="relu", name="conv1_1")`
>   x = Convolution2D(64, 3, 3, activation='relu',name='conv1_1',border_mode ='same')(inputs)
> Traceback (most recent call last):
>   File "p.py", line 7, in <module>
>     model = VGG_19_GAP_functional("aesthestic_gap_weights_1_tensorflow.h5", heatmap=False)
>   File "/home/website/i4/piqual/model.py", line 16, in VGG_19_GAP_functional
>     x = Convolution2D(64, 3, 3, activation='relu',name='conv1_1',border_mode ='same')(inputs)
>   File "/usr/lib/python2.7/site-packages/keras/engine/topology.py", line 569, in __call__
>     self.build(input_shapes[0])
>   File "/usr/lib/python2.7/site-packages/keras/layers/convolutional.py", line 125, in build
>     raise ValueError('The channel dimension of the inputs '
> ValueError: The channel dimension of the inputs should be defined. Found `None`.

here is my code:

```
import os
import numpy as np
import cv2
from keras.models import load_model
from model import VGG_19_GAP_functional
from utils import preprocess_image,deprocess_image
model = VGG_19_GAP_functional("aesthestic_gap_weights_1_tensorflow.h5", heatmap=False)

file=open("1.jpg", "rw+")
file.seek(0)
original_img = cv2.resize(cv2.imdecode(np.fromstring(file.read(), np.uint8), cv2.IMREAD_COLOR), (224,224))
im = preprocess_image(original_img)
out = model.predict(im)
```

so how to solve this problem? thanks in advance

**Comment by handyzeng** [comment]
I have the same issue. Have you already solve the problem?

**Comment by handyzeng** [comment]
You should use Keras 1
